import { Injectable } from '@angular/core';
import { Lembrete } from '../model/lembrete';

@Injectable({
  providedIn: 'root'
})
export class LembretesService {
  // Atributos
  private lembretes = new Array<Lembrete>();
  private autoGeneratedId = 0;

  // Métodos
  constructor() { }

  inserir(lembrete: Lembrete): void {
    lembrete.id = this.autoGeneratedId++;
    this.lembretes.push(lembrete);
    this.salvar();
  }
  
  exibir(): Array<Lembrete> {
    this.carregar();
    return this.lembretes;
  }

  remover(id: number): void {
    for(let i = 0; i < this.lembretes.length; i++) {
      if(this.lembretes[i] != null && this.lembretes[i].id == id) {
          this.lembretes.splice(i, 1);
          break;
      }
    }

    this.salvar();
  }

  atualizar(lembrete: Lembrete): void {
    for(let i = 0; i < this.lembretes.length; i++) {
      if(this.lembretes[i] != null && this.lembretes[i].id == lembrete.id) {
          this.lembretes[i] = lembrete;
          break;
      }
    }

    this.salvar();
  }

  salvar(): void {
    localStorage.setItem('lembretes', JSON.stringify(this.lembretes));
    localStorage.setItem('lembreteAutoGeneratedId', this.autoGeneratedId.toString());
  }

  carregar(): void {
    const guardarValores = localStorage.getItem('lembretes');

    if(guardarValores) {
      this.lembretes = JSON.parse(guardarValores);
    } else {
      this.lembretes = new Array<Lembrete>();
    }

    const autoGenId = localStorage.getItem('lembreteAutoGeneratedId');

    if(autoGenId) {
      this.autoGeneratedId = Number(autoGenId);
    }
  }
}
